---
- hosts: migracion
  become: true
  tasks:
    - name: Update
      apt : update_cache=yes
    - name: Upgrade
      apt : upgrade=dist
    - name: Instalando paquetes
      apt: name={{ item }} update-cache=yes state=present
      with_items:
        - python-setuptools
        - python3-dev
        - python3-pip
        - python-virtualenv
        - nginx-full
        - mercurial
        - python-mysqldb
        - git
        - chromium-browser
        - htop
        - software-properties-common
        - php
    - name: pip
      easy_install:
          name=pip
    - name: Actualizando pip
      command: pip install --upgrade pip
    - name: Complementos de PHP
      apt: pkg={{ item }} state=present update_cache=true
      with_items:
        - php-pear
        - php-dev
        - php-zip
        - php-curl
        - php-gd
        - php-mysql
        - php-mcrypt
        - php-xml
        - php-fpm
        - php-gettext
        - php-mbstring
        - php-xmlrpc
    - name: Agregando archivo de virtual host
      action: template src=team.com dest=/etc/nginx/sites-available/team.com
    - name: Agrega a /etc/hosts la ip local
      shell: echo "192.168.14.83 team.com" >> /etc/hosts
    - name: Crear enlace simbólico a team.com
      file: src=/etc/nginx/sites-available/team.com dest=/etc/nginx/sites-enabled/team.com state=link
      notify:
        - Reiniciando NGINX
    - name: Agregando key MariaDB
      shell: apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
    - name: Agregando repositorio MariaDB
      shell: add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://mirror.nodesdirect.com/mariadb/repo/10.2/ubuntu xenial main'
    - name: Upgrade
      shell: apt update
    - name: Instalando MariaDB
      apt: pkg=mariadb-server state=present update_cache=true
    - name: Driver mysqli para PHP
      apt: pkg=php-mysqlnd state=present update_cache=true
    - name: Configuración MariaDB para conexión desde cualquier IP
      lineinfile: dest=/etc/mysql/my.cnf regexp="^bind-address" line="bind-address=0.0.0.0"
    - name: Creando usuario team_dev
      mysql_user: name=team_dev host="%" password=team_dev priv=*.*:ALL state=present
    - name: Creando usuario root
      mysql_user: name=root host="%" password=team_dev priv=*.*:ALL state=present
    - name: Creando usuario iintegrausr
      mysql_user: name=iintegrausr host="%" password=team_dev priv=*.*:ALL state=present
      notify:
        - Actualiza Privilegios MariaDB
    #- name:  Creando base de datos db_team
      #mysql_db:
        #name: db_team
        #state: present
    #- name: Copiando DB
      #copy:
        #src: db_team.sql
        #dest: /tmp
    #- name: "Preparando la importacion"
      #shell: sed -i '1s/^/[mysqld]\n/' /etc/mysql/my.cnf
      #args:
        #warn: false
    #- name: Reiniciando MariaDB
      #service: name=mysql state=restarted
    #- name: Restaurando Base de Datos
      #mysql_db:
        #name: db_team
        #state: import
        #target: /tmp/db_team.sql
    - name: Clonando Repositorio con la rama de migracion
      shell: hg clone 'https://eduardodominguez:passwodrd@bitbucket.org/integramx/webteam_v1' /home/triplei/web_team -b migracion-v2
    - name: Cambiando permisos
      file: path=/home/triplei/web_team owner=triplei group=triplei mode=0775 state=directory recurse=yes
    - name: Update
      apt : update_cache=yes
    - name: Upgrade
      apt : upgrade=dist
    - name: Reiniciando Servidor
      shell: reboot
  handlers:
    - name: Reiniciando NGINX
      service: name=nginx state=restarted
    - name: Actualiza Privilegios MariaDB
      shell: mysql -u team_dev --password=team_dev -e "FLUSH PRIVILEGES;"