---
- hosts: migracion
  become: yes
  tasks:
    - name: Install apt-get packages
      apt: name={{ item }} update-cache=yes state=present cache_valid_time=3600
      with_items:
        - python-setuptools
        - python3-dev
        - python3-pip
        - python-virtualenv
        - nginx-full
        - mercurial

    - name: Install pip
      easy_install:
          name=pip

    - name: Upgrade pip
      command: pip install --upgrade pip

